### PR TITLE
update to go1.18, and general refactor / cleanup / fixes

### PR DESCRIPTION
**Pull request by thaJeztah**
Sorry for the massive number of commits / changes. This started as a bit of a fun "lunchtime" project to understand what this module does, and with the initial intent to cleanup some small things I spotted while reviewing https://github.com/moby/moby/pull/44458#pullrequestreview-1181617950, but it ended up in doing a bit more.

I split the changes into small commits, describing each step in the commit message, so it's best to review per-commit (and probably best to (if accepted) merge _without squashing_ to keep the information in history 😅 🙏 .

If there's any changes in there that should be dropped; happy to do so 👍

### CODE REVIEW

**Comment by thaJeztah** [comment]
@AdamKorcz ptal 🤗

**Comment by AdamKorcz** [comment]
Thank you for the PR! I will take a look over the weekend.

**Review by AdamKorcz — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
Thanks!!

**Pull request merged**
